### ISSUE TITLE
parsePrice() and closePrice() sometimes breaks.

### ISSUE THREAD

**Issue by badsko** [badsko/schtock#1]
This is seen in docker logs. Container is restarted.
```
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                                NAMES
<id>                schtock:1.0                   "python ./schtock.py"    12 hours ago        Up 36 minutes                                                            naughty_volhard
```

```
20:00
Traceback (most recent call last):
  File "./schtock.py", line 36, in <module>
    current = parsePrice()
  File "./schtock.py", line 24, in parsePrice
    price=soup.find('div',{'class': cls}).find('span').text.replace(',','')
AttributeError: 'NoneType' object has no attribute 'find'
20:01
```

```
22:57
Traceback (most recent call last):
  File "./schtock.py", line 37, in <module>
    close = closePrice()
  File "./schtock.py", line 31, in closePrice
    price=soup.find('td',{'data-test': cls}).find('span').text.replace(',','')
AttributeError: 'NoneType' object has no attribute 'find'
22:57
```

**Comment by badsko** [comment]
This was Yahoo rate limiting 503 Service Unavailable. Change to Avanza instead.
