### ISSUE TITLE
Issue with lowPrice and highPrice functions returning nothing.

### ISSUE THREAD

**Issue by badsko** [badsko/schtock#3]
```
19:59
Traceback (most recent call last):
  File "./schtock.py", line 48, in <module>
    low = +float(lowPrice())
  File "./schtock.py", line 37, in lowPrice
    p = soup.find('span',{'class': c}).text.replace('\xa0','').replace(',','.').replace('-','')
AttributeError: 'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "./schtock.py", line 47, in <module>
    high = +float(highPrice())
  File "./schtock.py", line 30, in highPrice
    p = soup.find('span',{'class': c}).text.replace('\xa0','').replace(',','.').replace('-','')
AttributeError: 'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "./schtock.py", line 48, in <module>
    low = +float(lowPrice())
  File "./schtock.py", line 37, in lowPrice
    p = soup.find('span',{'class': c}).text.replace('\xa0','').replace(',','.').replace('-','')
AttributeError: 'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "./schtock.py", line 47, in <module>
    high = +float(highPrice())
  File "./schtock.py", line 30, in highPrice
    p = soup.find('span',{'class': c}).text.replace('\xa0','').replace(',','.').replace('-','')
AttributeError: 'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "./schtock.py", line 46, in <module>
    current = +float(currentPrice())
  File "./schtock.py", line 23, in currentPrice
    p = soup.find('span',{'class': c}).text.replace('\xa0','').replace(',','.').replace('-','')
AttributeError: 'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "./schtock.py", line 46, in <module>
    current = +float(currentPrice())
  File "./schtock.py", line 23, in currentPrice
    p = soup.find('span',{'class': c}).text.replace('\xa0','').replace(',','.').replace('-','')
AttributeError: 'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "./schtock.py", line 48, in <module>
    low = +float(lowPrice())
  File "./schtock.py", line 37, in lowPrice
    p = soup.find('span',{'class': c}).text.replace('\xa0','').replace(',','.').replace('-','')
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by badsko** [comment]
Added variable init inside the functions and try to catch the error and not crash the container.
```
def lowPrice():
    p = 1
    r = requests.get(url)
    soup = bs4.BeautifulSoup(r.text,'lxml')
    c = 'lowestPrice SText bold'
    try:
        p = soup.find('span',{'class': c}).text.replace('\xa0','').replace(',','.').replace('-','')
    except AttributeError:
        print (datetime.now().strftime('%H:%M'), ' An error occured.')
    return p
```
